site_name: WARG Docs
site_url: http://www.docs.uwarg.com
repo_url: https://github.com/UWARG/
site_author: University of Waterloo Aerial Robotics Group
site_favicon: favicon.ico
copyright: Copyright <a href="http://www.uwarg.com"> University of Waterloo Aerial Robotics Group</a>
theme: readthedocs
google_analytics: ['UA-68186801-2', 'docs.uwarg.com']

pages:
- Home: index.md
- Bootcamps:
  - Mechanical: bootcamp/mechanical.md
  - Computer Vision: bootcamp/computer-vision.md
  - Electrical: bootcamp/electrical.md
  - Groundstation: bootcamp/groundstation.md
  - Embedded Software: bootcamp/embedded.md
  - RC Car Competition: bootcamp/rccompetition.md
- Tutorials:
  - Git and Github: tutorials/git.md
  - Using the terminal: tutorials/shell.md
- Groundstation:
  - Table of Contents: groundstation/index.md
  - Introduction: groundstation/introduction.md
  - What you need to know: groundstation/what-you-need-to-know.md
  - Installation: groundstation/installation.md
  - Tutorial: groundstation/tutorial.md
  - Project Structure: groundstation/project-structure.md
  - Contributing: groundstation/contributing.md
  - Documenting: groundstation/documenting.md
  - Additional Resources: groundstation/resources.md
- ZeroPilot:
  - Table of Contents: zeropilot/index.md
  - Pinout Reference: zeropilot/pinout_reference.md
  - Hardware: zeropilot/hardware.md
- Network:
  - Data Relay: network/data_relay.md
  - Multi Echo: network/multi_echo.md
- Computer Vision:
  - Table of Contents: computer-vision/index.md
  - Building the project [Linux]: computer-vision/Building-the-project-[Linux].md
  - Building the project [Windows]: computer-vision/Building-the-project-[Windows].md
  - Coding Conventions: computer-vision/Coding-Conventions.md
  - Contributing: computer-vision/Contributing.md
  - Using the WARG computer environment: computer-vision/Using-the-WARG-server-environment.md
  - Writing Tests: computer-vision/Writing-Tests.md
- Mechanical:
  - Table of Contents: mechanical/index.md
  - CAD Guidelines: mechanical/cad-guidelines.md
  - 3D Printing Guidelines: mechanical/3d-printing-guidelines.md
  - GrabCad: mechanical/grabcad.md
- PicPilot:
  - Table of Contents: picpilot/index.md
  - Introduction: picpilot/introduction.md
  - PID Loops: picpilot/pid-loops.md
  - PWM and IO: picpilot/pwm-io.md
  - UART: picpilot/uart.md
  - SPI: picpilot/spi.md
  - Direct Memory Access: picpilot/direct-memory-access.md
  - I2C: picpilot/i2c.md
  - Datalink: picpilot/datalink.md
  - Analog to Digital Converter: picpilot/analog-to-digital-converter.md
  - Sensors and Peripherals: picpilot/sensors-and-peripherals.md
  - Attitude Control: picpilot/attitude-control.md
  - Path Management: picpilot/path-management.md
  - Resources: picpilot/resources.md
  - FAQ: picpilot/faq.md
